export default {
  'Bakersfield': 'assets/bakersfield.svg',
  'Channel Islands': 'assets/channelIslands.svg',
  'Chico': 'assets/chico.svg',
  'Dominguez Hills': 'assets/dominguezHills.svg',
  'East Bay': 'assets/eastBay.svg',
  'Fresno': 'assets/fresno.svg',
  'Fullerton': 'assets/fullerton.svg',
  'Humboldt': 'assets/humboldt.svg',
  'Long Beach': 'assets/longBeach.svg',
  'Los Angeles': 'assets/losAngeles.svg',
  '​Maritime Academy': 'assets/maritime.svg',
  'Monterey Bay': 'assets/montereyBay.svg',
  'Northridge': 'assets/northridge.svg',
  'Pomona': 'assets/pomona.svg',
  'Sacramento': 'assets/sacramento.svg',
  'San Bernardino': 'assets/sanBernardino.svg',
  'San Diego': 'assets/sanDiego.svg',
  'San Francisco': 'assets/sanFrancisco.svg',
  'San José': 'assets/sanJose.svg',
  'San Luis Obispo': 'assets/sanLuisObispo.svg',
  'San Marcos': 'assets/sanMarcos.svg',
  'Sonoma': 'assets/sonoma.svg',
  'Stanislaus': 'assets/stanislaus.svg'
}